### ISSUE TITLE
Error on https://roxik.com/v/2/

### ISSUE THREAD

**Issue by rredford** [ruffle-rs/ruffle#10297]
Reliably crashes each time. Not sure what is happening. Happens instantly after I click play button

# Error Info
Error name: Error
Error message: panicked at 'No uniform for push constant', /home/runner/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/c585127/wgpu-hal/src/gles/command.rs:674:17
Error stack:
```
339/getImports/imports.wbg.__wbg_new_15d3966e9981a196@moz-extension://1028ad4f-063d-4d9a-9959-3b4f2830ed49/dist/339.js:2154:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h0f330faf47f8cac8@:wasm-function[7830]:0x7cb3fc
std::panicking::rust_panic_with_hook::h8d0a63d0479a36c8@:wasm-function[5304]:0x712d4e
core::panicking::panic_fmt::h2a7f454a5f5da218@:wasm-function[7727]:0x7c6ca1
wgpu_hal::gles::command::<impl wgpu_hal::CommandEncoder<wgpu_hal::gles::Api> for wgpu_hal::gles::CommandEncoder>::set_push_constants::hb0f98a17a9ccd291@:wasm-function[3223]:0x6218cb
<T as wgpu::context::DynContext>::command_encoder_end_render_pass::h8704e0e2f5b9b5ff@:wasm-function[7359]:0x7b3702
<wgpu::RenderPass as core::ops::drop::Drop>::drop::hd886a742114c09bd@:wasm-function[6214]:0x755713
<ruffle_render_wgpu::backend::WgpuRenderBackend<T> as ruffle_render::backend::RenderBackend>::apply_filter::h4e21af0bf9837d6b@:wasm-function[1254]:0x3a74cb
ruffle_core::avm2::globals::flash::display::bitmap_data::apply_filter::hacb027b994c298e4@:wasm-function[684]:0x24c1f9
ruffle_core::avm2::function::Executable::exec::h27c247d7dfa8e105@:wasm-function[872]:0x2e2468
ruffle_core::avm2::object::TObject::call_property::he7481586939ad550@:wasm-function[1036]:0x3408e1
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call_property::h3b68a4dc368eeb72@:wasm-function[2643]:0x599d10
ruffle_core::avm2::activation::Activation::do_next_opcode::hfd09a5558ca8c57f@:wasm-function[521]:0x115bb9
ruffle_core::avm2::activation::Activation::run_actions::hd2ce3c0da9e6acb3@:wasm-function[3640]:0x66671e
ruffle_core::avm2::function::Executable::exec::h27c247d7dfa8e105@:wasm-function[872]:0x2e35b1
<ruffle_core::avm2::object::class_object::ClassObject as ruffle_core::avm2::object::TObject>::construct::hff7816bcb493403d@:wasm-function[3834]:0x681fc0
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::construct::h71079a42e48c9232@:wasm-function[1713]:0x4857e1
ruffle_core::avm2::activation::Activation::do_next_opcode::hfd09a5558ca8c57f@:wasm-function[521]:0x116f3f
ruffle_core::avm2::activation::Activation::run_actions::hd2ce3c0da9e6acb3@:wasm-function[3640]:0x66671e
ruffle_core::avm2::function::Executable::exec::h27c247d7dfa8e105@:wasm-function[872]:0x2e35b1
<ruffle_core::avm2::object::Object as ruffle_core::avm2::object::TObject>::call::h775d8069c46cd0c4@:wasm-function[937]:0x3116ae
ruffle_core::avm2::events::dispatch_event_to_target::hd47f0cd946c64f46@:wasm-function[827]:0x2c3ee7
ruffle_core::avm2::events::dispatch_event::h25a7b7cc9ea0db07@:wasm-function[958]:0x31c8f1
ruffle_core::avm2::Avm2::dispatch_event::h332498db4c3028d6@:wasm-function[4627]:0x6d4d6f
ruffle_core::display_object::container::dispatch_added_to_stage_event_only::h09ce9bb76b14da7e@:wasm-function[1741]:0x48ca00
ruffle_core::display_object::TDisplayObject::on_construction_complete::h008a672993ca33c2@:wasm-function[1011]:0x334a21
<ruffle_core::display_object::movie_clip::MovieClip as ruffle_core::display_object::TDisplayObject>::construct_frame::h7ea8cbb7d0384e4d@:wasm-function[596]:0x1c0e91
<ruffle_core::display_object::DisplayObject as ruffle_core::display_object::TDisplayObject>::construct_frame::h1d939deed3e98028@:wasm-function[3881]:0x68aa35
ruffle_core::frame_lifecycle::catchup_display_object_to_frame::hdc7dd744fcd37ace@:wasm-function[5894]:0x73e99c
ruffle_core::loader::Loader::preload_tick::hf38a5c1cec72dadc@:wasm-function[815]:0x2b85bc
ruffle_web::Ruffle::tick::hf646f17d22d6c327@:wasm-function[673]:0x23742f
ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::he8f0500645eb77fb@:wasm-function[9429]:0x80464f
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h158d5e83cc37d2f8@:wasm-function[8333]:0x7d7102
__wbg_adapter_57@moz-extension://1028ad4f-063d-4d9a-9959-3b4f2830ed49/dist/339.js:278:10
real@moz-extension://1028ad4f-063d-4d9a-9959-3b4f2830ed49/dist/339.js:259:20

```
AVM2 stack:
```
    at flash.display::BitmapData/flash::display::BitmapData::applyFilter()
    at M3D_Model_BG()
    at M3D_controller/init()
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: loader.swf
Param scale: noscale
Param salign: tl
Param allowscriptaccess: always
Param menu: false
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://roxik.com/v/2/
SWF URL: https://roxik.com/v/2/loader.swf

# Browser Info
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0
Platform: Linux x86_64
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-03-11
Channel: nightly
Built: 2023-03-11T00:19:08.742Z
Commit: f4354a638e952fa4f9d39efd63631ef3daba437f
Is extension: true

# Metadata
width: 864
height: 490
frameRate: 30
numFrames: 1
swfVersion: 9
backgroundColor: #000000
isActionScript3: true
uncompressedLength: 43257

**Comment by n0samu** [comment]
Should be fixed by #11753 and #11750

**Comment by rredford** [comment]
Seems to still crash here, or is browser plugin updated less often?

**Comment by n0samu** [comment]
Yeah, the Firefox extension has not been updated yet. This should be fixed in nightly 2023-06-27 and newer.
