### ISSUE TITLE
Uncharted 2 Among Thieves: Broken Movie and unplayable game portion

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10294]
### Describe the bug

https://www.newgrounds.com/portal/view/513771?emulate=flash
This SWF is built half advertisement for Uncharted 2, half flash game to promote it, however there are 2 issues with this game.

1: If you try watching the movie by clicking on the movie button, it will toss these up in the logs.

Got RustError("ArgumentError: Child not a valid display object") when constructing AVM2 side of movie clip of type fl.video::FLVPlayback

Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x1e04d88 }) to handler FunctionObject(FunctionObject { ptr: 0x594e1e8 }) : TypeError: Error # 1009: Cannot access a property or method of a null object reference. (accessing field: autoPlay)

2: If you try playing the game portion of the swf, then as soon as you get past the first cutscene, you'll be stuck with a black screen as this pops up in the logs.

Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0x1dd26a0 }) to handler FunctionObject(FunctionObject { ptr: 0x1723740 }) : RustError("Param <Unnamed Parameter> (index 1) was missing when calling ")

### Expected behavior

You should be able to watch the trailer for the game in the swf and the game portion of the swf should be playable.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by Lord-McSweeney** [comment]
The `Got RustError("ArgumentError: Child not a valid display object") when constructing AVM2 side of movie clip of type fl.video::FLVPlayback` error also shows up on Weed to Wonder.

**Comment by waspennator** [comment]
The latest nightly has fixed the game portion of this SWF, it starts now and i'm capable of completing level 1 on web, though I haven't tested further since performance takes a dip during level 2 on web.

The SWF still breaks though if you try to watch the movie section.

**Comment by waspennator** [comment]
Tested the game out on desktop after another user reported it, Level 2 has explosive barrels strewn about the place and if you explode one of them, that just seems to cause a weird explosion effect before making Nathan Drake vanish from the game, the audio annoyingly looping.

**Comment by emgfc** [comment]
@waspennator this should fix it: https://github.com/ruffle-rs/ruffle/pull/10344

**Comment by waspennator** [comment]
> @waspennator this should fix it: #10344

Can confirm at least on desktop that the explosive barrels no longer cause Drake to vanish into thin air if you blow them up. The explosion effects when they blow up seem to look better as well.

**Comment by n0samu** [comment]
Even though FLV support has been added, the video still doesn't play when the SWF is loaded in the desktop app or the extension's player page. (On NG, the request is blocked by CORS.) These warnings might be related:
`WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.net.NetStream.time getter`
`WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.net.NetStream.seek()`

**Comment by n0samu** [comment]
The audio plays now, but the video still doesn't show up.
```
WARN ruffle_core::stub: Encountered stub: AVM2 flash.net.NetStream.bufferTime setter
WARN ruffle_core::stub: Encountered stub: AVM2 flash.net.NetStream.soundTransform setter
WARN ruffle_core::stub: Encountered stub: AVM2 flash.net.NetStream.soundTransform getter
```
