### ISSUE TITLE
Ruffle  can't stay open

### ISSUE THREAD

**Issue by Croworbit** [ruffle-rs/ruffle#12378]
### Describe what you were doing

I'm not sure why, but Ruffle just crashes after extended periods of time
I'm used to opening a flash game with flash player on websites or using projectors, for long periods of time, like obscenely long, up to weeks of the program running in the background or as my computer is locked

sometimes I just listen to game soundtracks this way, or so I don't forget to get back to them
Ruffle seems to stop working within 5 seconds (I counted) when my PC is locked or the screensaver comes on, and doesn't last a week

### What does the crash message say?

it says something about being unavailable

### Ruffle Version

2023-07-28

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information
I need the stability

**Comment by Lord-McSweeney** [comment]
This is a known bug that occurs when the GPU decides to drop all of Ruffle's resources because the GPU has gone out of use (e.g. computer going to sleep). Currently, Ruffle has no way to store the resources and re-upload them to the GPU when the GPU is available again.

**Comment by Croworbit** [comment]
that is pretty frustrating, but makes sense
is this planned to be fixed in the future?

**Comment by Lord-McSweeney** [comment]
Hopefully we can fix it soon, since it's a big annoyance to many users, but it would require large refactoring of the renderer code. Since it's not really a breaking issue to most users, it's a pretty low-priority issue.

**Comment by Croworbit** [comment]
This is no longer relevant, and is fixed.
Ruffle stays open on switching to screensaver, on locking of computer, and will stay open for at least a day by my testing. windows and linux.

(I haven't tested keeping ruffle open for a week or more or mac)

**Comment by kjarosh** [comment]
Not entirely sure, but could have been fixed by https://github.com/ruffle-rs/ruffle/pull/16699

**Comment by Rhlp-Engineering** [comment]
it's not fixed for me, and the entire computer crashes whenever ruffle crashes for some reason. yipee. :s

**Comment by kjarosh** [comment]
> it's not fixed for me, and the entire computer crashes whenever ruffle crashes for some reason. yipee. :s

Please file a new issue
