### ISSUE TITLE
The last stand union city - yellow screen

### ISSUE THREAD

**Issue by ActionWavele** [ruffle-rs/ruffle#12445]
### Describe the bug

someone told me this game works perfect on ruffle, but it doesn't yet

https://github.com/ruffle-rs/ruffle/assets/120395932/9cb7e09f-9074-493d-9428-71586d79ec10

### Expected behavior

ther should be no yellow blocking the view

### Affected platform

Desktop app

### Operating system

windows 8

**Comment by Zinc-Exclamation** [comment]
isn't this https://github.com/ruffle-rs/ruffle/issues/5516?

**Comment by MartySVK** [comment]
this was fixed....what version of Ruffle do you use?

**Comment by ActionWavele** [comment]
> this was fixed....what version of Ruffle do you use?

2 days ago I was using 2023-07-30
today I am using 2023-08-01...
does it matter?
it still occurs

you can try it on the latest builds if you don't believe me

**Comment by ActionWavele** [comment]
it happens when I make the screen bigger
but this doesn't happen with the projector
not even if I try and force it by going full screen

**Comment by ActionWavele** [comment]
I think this also happens on the flash projector.
dang
I looked for similar issues and it seems like https://github.com/ruffle-rs/ruffle/issues/12338 is the closest relevant issue

Can anyone else test this?
I tested it on windows with the flash projector

**Comment by Zinc-Exclamation** [comment]
it happens on linux FP, too

**Comment by Benman2785** [comment]
when using a resolution 76:40 it works (yet it has other bugs)
