### ISSUE TITLE
Barbie Driving Slacking: Incorrect graphics rendering

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#12584]
### Describe the bug

In the game **'Barbie Driving Slacking'**, the graphics are not the same as the original and appear broken.

[barbie-driving-slacking.zip](https://github.com/ruffle-rs/ruffle/files/12268516/barbie-driving-slacking.zip)

![image](https://github.com/ruffle-rs/ruffle/assets/75052171/49dbe2a3-a840-4247-bf99-69059ac2e6bd)

1. Button and the car has a rough border, unlike the original. (You can see by zooming in on the photo).
2. No text is displayed at the bottom of the Y8 logo.
3. Barbie's hair shows blue graphic broken pixels.

### Expected behavior

The three graphical issues mentioned above should be resolved.

### Affected platform

Desktop app

### Operating system

Windows 10 22H2

### Browser

Google Chrome 115

**Comment by n0samu** [comment]
1. I think the rough outlines are just a subtle difference in antialiasing, not something Ruffle can easily fix.
2. The missing text on the Y8 logo needs TLF text support at least.
3. The broken blue pixels in the Barbie sprite seems to be the same issue as #12136. It is also composed of weird CMYK JPEGs.

**Comment by SuchAFuriousDeath** [comment]
@n0samu 3. is fixed with #12592

**Comment by n0samu** [comment]
Text is still missing on the Y8 logo even though TLF is partially implemented/stubbed now

**Comment by SuchAFuriousDeath** [comment]
This needs CFF font support I think.
EDIT: Actually it's something with clip rects it seems. The cliprect around the text is too small.
