### ISSUE TITLE
on the firefox xpi extension

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#1274]
I have just installed the `.xpi` extension on Firefox and I found two issues:

1. I had to enable the installation of unsigned extensions. It worked this time, but I don’t think it will work with newer versions of Firefox.

1. Version number is too generic: `Ruffle version: 0.1.0`.

Just in case it helps.

**Comment by ousia** [comment]
Updating the issue three months after reporting it.

Version numbering is fine now, since it displays build date.

Having unsigned versions makes it really hard to install for novice users (even with animations that work perfectly fine with Ruffle).

I cannot suggest friends to install Ruffle. I don’t want them to get mad with me.

Just in case, it helps considering upgrading this issue.

**Comment by relrelb** [comment]
Fixed by #4021.

**Comment by ousia** [comment]
@Herschel, many thanks for #4021.

I wonder whether `Souind.position()` could be implemented now.

@relrelb fixes some issues #4026 with `Sound.duration()`, but '`Sound.position()` is still missing.

Many thanks for your excellent work.
