### ISSUE TITLE
Evoland (Linux Steam version)

### ISSUE THREAD

**Issue by Firlaev-Hans** [ruffle-rs/ruffle#13426]
### Describe the bug

**(Read _Additional Information_ first)**

The game starts normally, but besides some small issues being a little slow and laggy and missing music, as well as playing sound effects in the initial starting area before sound effects are even unlocked, you can't progress very far at all, because as soon as you unlock 16 color graphics (~1-2 minutes into the game), Ruffle encounters this issue:
```
thread 'main' panicked at 'Found ignore_sampler in SamplerField { filter: Linear, mipmap: Disable, wrapping: Clamp, dimension: TwoD, special: Special { ignore_sampler: true }, texture_lod_bias: 0, reg_num: 0, reg_type: Sampler }', render/naga-agal/src/builder.rs:1148:21
stack backtrace:
   0:     0x5600f5ad7a31 - std::backtrace_rs::backtrace::libunwind::trace::h66dc1c6acf794faa
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5600f5ad7a31 - std::backtrace_rs::backtrace::trace_unsynchronized::ha80d20099a67f790
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5600f5ad7a31 - std::sys_common::backtrace::_print_fmt::h7b959d43f35f16d4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5600f5ad7a31 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdaa196410d9ee0b9
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5600f5b08c1f - core::fmt::rt::Argument::fmt::h0ddfbbe8be3f80d0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/rt.rs:138:9
   5:     0x5600f5b08c1f - core::fmt::write::h66b3c629f3d623e4
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/fmt/mod.rs:1094:21
   6:     0x5600f5ad2fa7 - std::io::Write::write_fmt::hb6d80fba4115e0c2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/io/mod.rs:1714:15
   7:     0x5600f5ad7845 - std::sys_common::backtrace::_print::h1a49cfb0cf3cce17
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5600f5ad7845 - std::sys_common::backtrace::print::hca95c2d0055e42a2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5600f5ad8fe3 - std::panicking::default_hook::{{closure}}::hc03c01c56bca600c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:269:22
  10:     0x5600f5ad8d74 - std::panicking::default_hook::hb2cb5315b6634f1c
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:288:9
  11:     0x5600f4b5c251 - ruffle_desktop::init::{{closure}}::h9733ca96f53a2933
  12:     0x5600f5ad96de - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb3a915ffd78277c6
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/alloc/src/boxed.rs:2007:9
  13:     0x5600f5ad96de - std::panicking::rust_panic_with_hook::h75cd912a39a34e8a
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:709:13
  14:     0x5600f5ad9467 - std::panicking::begin_panic_handler::{{closure}}::h1498b46f7849e167
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:597:13
  15:     0x5600f5ad7e96 - std::sys_common::backtrace::__rust_end_short_backtrace::hd36a39b27b98086b
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/sys_common/backtrace.rs:151:18
  16:     0x5600f5ad91b2 - rust_begin_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
  17:     0x5600f4afea63 - core::panicking::panic_fmt::h98ef273141454c23
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
  18:     0x5600f4d7be22 - naga_agal::builder::NagaBuilder::process_agal::h8dce34db15164d78
  19:     0x5600f4d783f9 - naga_agal::agal_to_naga::ha24de904cb6b466b
AVM2 stack trace: 
        at flash.display3D::Context3D/flash::display3D::Context3D::drawTriangles()
        at h3d.impl::Stage3dDriver/draw()
        at h3d::Engine/renderBuffer()
        at h2d::Drawable/drawTile()
        at h2d::Bitmap/draw()
        at h2d::Sprite/drawRec()
        at h2d::Sprite/drawRec()
        at h2d::Scene/render()
        at h3d.scene::Scene/render()
        at h3d::Engine/render()
        at Game/update()
        at Game$/doUpdate()
        at MethodInfo-2710()
```

The exact same error also occurs when loading any preexisting savegame

### Expected behavior

Unlocking 16 color graphics or loading savegames should work normally.
Additionally, sound effects shouldn't play at all initially when starting a new game until the player opens the respective chest (instead the sounds start to play and are cut off), and music should work both in the main menu and after unlocking it in-game.

### Affected platform

Desktop app

### Operating system

Fedora Linux 38 / KDE Plasma Wayland

### Additional information

Evoland is a (paid) [Steam game](https://store.steampowered.com/app/233470/) made with Adobe AIR. But while the windows version of the game, as well as its much more complex sequel "Evoland 2", require AIR specific features, Evoland 1 has a **Linux version** (which is available though no longer listed on Steam) which was heavily tweaked compared to the windows version and **does not require Adobe AIR and can run in normal Flash player**.
Note that this game is different from [this issue](https://github.com/ruffle-rs/ruffle/issues/10560) which I think is about some super-early demo of the game.

See also this [Lightspark issue](https://github.com/lightspark/lightspark/issues/825).

The game is written in Haxe with the [heaps.io](https://heaps.io) game engine and makes use of Stage3D. It gets more technically complex as you play, starting with monochrome pixel graphics and ending with decent 3D graphics.
It uses local storage for savegames.

A re-release of Evoland 1 & 2 combined, called "Evoland Legendary Edition" exists on Steam but it is built as a native executable and doesn't use Flash in any way at all.

I can't publicly share the SWF since this is a paid game, though I could privately provide it to a developer on request. The SWF file is called game.dat, don't mind the extension.

**Comment by Lord-McSweeney** [comment]
@Aaron1011 pinging
```
                // FIXME - Flash Player seems to unconditionally use sampler overrides,
                // regardless of whether or not `ignore_sampler` is set. I haven't
                // found any real SWFs that use it, so let's panic so that get
                // get a bug report if it ever happens.
                if sampler_field.special.ignore_sampler {
                    panic!("Found ignore_sampler in {:?}", sampler_field);
                }
```

**Comment by Firlaev-Hans** [comment]
Oh, also, does it make sense to open issues for the Windows version of the game as well as for Evoland 2 even though they require Adobe AIR features, or is AIR compatibility out of scope for Ruffle?

**Comment by Aaron1011** [comment]
> Oh, also, does it make sense to open issues for the Windows version of the game as well as for Evoland 2 even though they require Adobe AIR features, or is AIR compatibility out of scope for Ruffle?

We may support AIR in the future, so you can go ahead and open issues for it.

Can you share the SWF with my privately (I'm on the Ruffle discord as @aaron1011)

**Comment by Lord-McSweeney** [comment]
Hmm, pressing enter shouldn't enter full-screen. IIRC ALT+Enter is the keybind to enter fullscreen.

**Comment by Lord-McSweeney** [comment]
> When placing a bomb in the 3D world, this error message appears in the terminal, but it doesn't affect gameplay: `ERROR ruffle_core::avm2::globals::flash::display3D::context_3d: Unknown culling "frontAndBack"`


This is because of this line:
https://github.com/ruffle-rs/ruffle/blob/3a658f5dec872218032a9545ae985dcbadd5c3d4/core/src/avm2/globals/flash/display3D/context_3d.rs#L246

This should be `frontAndBack`, not `front_and_back`.

**Comment by Lord-McSweeney** [comment]
> There is still absolutely no music. Sound effects work, but music does not.
The most likely reason for this is that Ruffle does not support the `MessageChannel` class. On the lightspark Evoland issue, this error is noted:
```
TypeError: Error #1014: Error #1014: Class flash.system::MessageChannel could not be found.
    at hxd.snd::MusicWorker/start()
    at Class/init()
    at Class/main()
    at boot_ae42/init()
    at boot_ae42/start()
    at boot_ae42/()
```

`hxd.snd::MusicWorker` is probably responsible for the music.

**Comment by Lord-McSweeney** [comment]
Save points might be related to the `SharedObject.setProperty` stub.

**Comment by Aaron1011** [comment]
After some testing, I've determiend the correct behavior of the `ignoresampler` flag. This is implemented in https://github.com/ruffle-rs/ruffle/pull/14164, which removes the panic.

**Comment by Aaron1011** [comment]
This is now fixed

**Comment by Firlaev-Hans** [comment]
> This is now fixed

Well, sort of. Music is still missing, presumably due to the lack of message channel support.

(Additionally there are still performance problems but maybe those don't need to be tracked here)

**Comment by Aaron1011** [comment]
Can you open a separate issue for the music problem?

**Comment by Lord-McSweeney** [comment]
The issue with sound effects being cut off instead of completely silenced at the start of the game is still present; see #23793
