### ISSUE TITLE
Evoland (Windows version / Adobe AIR)

### ISSUE THREAD

**Issue by Firlaev-Hans** [ruffle-rs/ruffle#13436]
### Describe the bug

For more information on the game itself see #13426.
This is about the Windows version which requires some Adobe AIR features.
In Ruffle, currently the game boots up to the main menu but doesn't show any menu text, instead throws an error:
```
2023-10-05T15:06:53.761773Z ERROR ruffle_core::tag_utils: Error running definition tag: DefineBitsJpeg2, got Couldn't register bitmap: Invalid PNG
2023-10-05T15:07:07.298784Z ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x564ccffd5b90 }) to handler FunctionObject(FunctionObject { ptr: 0x564ccd348040 }) : TypeError: Error #1010: A term is undefined and has no properties. (accessing field: %]'h)
```
The second error is repeated infinitely.
Also just like the with Linux version there's sound but no music.

In Lightspark without AIR support enabled actually gets a bit further, the main menu works but as soon as you try to start a game it throws an error because it uses Adobe AIR's `nativeProcess` to call `GetAch.exe`, which presumably has to do with Steam achievments.
Lightspark actually supports AIR when given the `--air` command line argument, with that the game mostly works there. Lightspark only stubs nativeProcess and the game works without that exe.

### Expected behavior

Ruffle should at least show the main menu correctly and with music, just like Lightspark even without AIR support.
Ideally Ruffle would implement or stub `nativeProcess` and the game should work normally

### Affected platform

Desktop app

### Operating system

Fedora Linux 38 / KDE Plasma Wayland

**Comment by Lord-McSweeney** [comment]
Here's some more verbose logging output:
```
2023-10-07T01:05:30.144567Z ERROR ruffle_core::tag_utils: Error running definition tag: DefineBitsJpeg2, got Couldn't register bitmap: Invalid PNG
2023-10-07T01:05:30.510729Z  WARN ruffle_core::display_object::movie_clip: Symbol class _res.[-*B cannot be assigned to invalid character id 54
2023-10-07T01:05:30.533739Z  WARN ruffle_core::stub: Encountered stub: AVM2 flash.system.Capabilities.language getter
2023-10-07T01:05:30.562867Z  WARN ruffle_core::stub: Encountered stub: AVM2 XML.namespace()
2023-10-07T01:05:30.562901Z  WARN ruffle_core::stub: Encountered stub: AVM2 Namespace.prefix getter
2023-10-07T01:05:30.692338Z  WARN ruffle_core::stub: Encountered stub: AVM2 flash.utils.Dictionary constructor with weak keys
2023-10-07T01:05:30.843200Z  WARN ruffle_core::stub: Encountered stub: AVM2 flash.display3D.Context3D.driverInfo getter
2023-10-07T01:05:30.881489Z  WARN ruffle_core::stub: Encountered stub: AVM2 flash.system.Capabilities.os getter
2023-10-07T01:05:38.144637Z  WARN ruffle_core::stub: Encountered stub: AVM2 flash.text.Font.enumerateFonts()
2023-10-07T01:05:46.417236Z ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x562da3e0b330 }) to handler FunctionObject(FunctionObject { ptr: 0x562da43d2240 }) : TypeError: Error #1010: A term is undefined and has no properties. (accessing field: %]'h)
	at YL::WN//9XQD()
	at xM;$/R1uz()
2023-10-07T01:05:46.432651Z ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x562da3a5cc00 }) to handler FunctionObject(FunctionObject { ptr: 0x562da43d2240 }) : TypeError: Error #1010: A term is undefined and has no properties. (accessing field: %]'h)
	at YL::WN//9XQD()
	at xM;$/R1uz()
2023-10-07T01:05:46.448909Z ERROR ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x562da3972b40 }) to handler FunctionObject(FunctionObject { ptr: 0x562da43d2240 }) : TypeError: Error #1010: A term is undefined and has no properties. (accessing field: %]'h)
	at YL::WN//9XQD()
	at xM;$/R1uz()
```
(last error repeated forever)

**Comment by Lord-McSweeney** [comment]
Note that `_res.[-*B` is actually `_res.[-*B\x03`. It seems to display fine in JPEXS- maybe Ruffle is getting confused between JPEGs and PNGs in `DefineBitsJpeg2`?

**Comment by Firlaev-Hans** [comment]
You can start a new game now but there are still issues:
![ruffleBrokenText](https://github.com/ruffle-rs/ruffle/assets/61254500/c0baf4ad-afd2-4d89-88de-fe21b140ef74)
![ruffleTextureFiltering](https://github.com/ruffle-rs/ruffle/assets/61254500/5802dcae-8156-4e03-a9cc-fa5d20633931)

Font rendering looks somewhat broken and as soon as you unlock color graphics, textures are filtered / blurred when they should be pixelated, and have black borders around them in some cases. Lightspark had a similar issue initially.
 
Also as soon as you try to load a savegame or do anything that would grant you an achievement you get an error about nativeProcess not being supported and the game locks up. As mentioned before that is an AIR feature but merely stubbing it would suffice for this game.

Music is also absent like in the Linux version, presumably due to a lack of MessageChannel support.
The `DefineBitsJpeg2` error is also still printed to the log.

**Comment by Lord-McSweeney** [comment]
On my end the rendering issue with blurred textures was fixed by #14164 - @Firlaev-Hans can you confirm?

**Comment by Firlaev-Hans** [comment]
Yup, the blurry textures are gone now.

**Comment by Lord-McSweeney** [comment]
This should have been entirely fixed by #17117, @Firlaev-Hans can you check?

**Comment by Firlaev-Hans** [comment]
> This should have been entirely fixed by #17117, @Firlaev-Hans can you check?

Font rendering is still broken but as far as I can tell all the save points etc. work now with AIR enabled. I'll try to do a full play through soon and report back whether or not there are any more issues.

**Comment by Firlaev-Hans** [comment]
So the game is definitely fully playable with no game-breaking issues. Besides the lack of music and broken fonts, these are the only issues I encountered:

- In this Diablo-esque part of the game ([savegame](https://github.com/user-attachments/files/16365380/evoSave.sol.zip)), the floor textures in the first big room are stretched and glitchy (just load the save and walk north), although this goes away once the player unlocks "Ambient Light"
![Screenshot_20240724_185830](https://github.com/user-attachments/assets/c0eee622-3540-4381-864e-e5dca83a3d6a)
(just load the save and walk north), although this goes away once the player unlocks "Ambient Light"
- During that same part, performance drops to almost unplayable levels whenever there are lots of enemies on screen at once

**Comment by Lord-McSweeney** [comment]
Font rendering is now working properly, probably thanks to one of kjarosh's recent PRs

**Comment by Lord-McSweeney** [comment]
The PNG error was fixed by #19863.
