### ISSUE TITLE
[General] Bitmaps look corrupted

### ISSUE THREAD

**Issue by pikuse** [ruffle-rs/ruffle#13774]
### Describe the bug

Bitmaps have a yellowy and blue look to them.
To reproduce, load any Flash movie with visible bitmaps.

![image](https://github.com/ruffle-rs/ruffle/assets/109040953/06a05f54-4d63-4e9a-976f-bf7da938fa94)

### Expected behavior

Bitmaps should look like this.

![image](https://github.com/ruffle-rs/ruffle/assets/109040953/cd64e75c-5a88-4314-af4f-b6da70e80900)

### Affected platform

Browser's extension

### Operating system

Windows 10 64-bit

### Browser

Microsoft Edge 118.0.2088.69

### Additional information

No flags are enabled.
Online demo is also affected by this.
Videos aren't affected.
It wasn't like this on older versions of Ruffle.

![image](https://github.com/ruffle-rs/ruffle/assets/109040953/d8ffa423-51e5-43b0-a098-24d25030e16a)

**Comment by n0samu** [comment]
Please provide a link or attachment containing the SWF file affected by the problem.

**Comment by pikuse** [comment]
https://aidn.jp/ep

This is a general issue impacting every movie loaded by Ruffle from a webserver, local movies work fine.

**Comment by Daisyfan1995** [comment]
only me occurs in Edge (beta channel) in some games, how papa´s games appears bad graphics error.
![papa wingeria bad graphics](https://github.com/ruffle-rs/ruffle/assets/65993904/1086d19e-0552-4750-95d2-75d56e7aa528)
Lucky, its bug is fixed. for new versions of microsoft edge. for (Beta Channel Insiders)

**Comment by n0samu** [comment]
I have not been able to reproduce this in Edge 118.0.2088.76. Is the problem still occurring for you in that version?

**Comment by pikuse** [comment]
It seems to still be occuring to me, with no way of fixing it.

**Comment by n0samu** [comment]
@pikuse Please right-click the content, click "Copy Debug Info" and paste the info here. Thanks!

**Comment by pikuse** [comment]
# Player Info
Allows script access: true
Renderer: wgpu
Adapter Backend: Gl
Adapter Name: "ANGLE (NVIDIA, NVIDIA GeForce GTX 970 (0x000013C2) Direct3D11 vs_5_0 ps_5_0, D3D11)"
Adapter Device Type: Other
Adapter Driver Name: ""
Adapter Driver Info: ""
Enabled features: Features(TEXTURE_COMPRESSION_BC | TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES | PUSH_CONSTANTS | SHADER_UNUSED_VERTEX_OUTPUT)
Available features: Features(CLEAR_TEXTURE | MULTIVIEW)
Current limits: Limits { max_texture_dimension_1d: 16384, max_texture_dimension_2d: 16384, max_texture_dimension_3d: 2048, max_texture_array_layers: 256, max_bind_groups: 4, max_bindings_per_bind_group: 1000, max_dynamic_uniform_buffers_per_pipeline_layout: 8, max_dynamic_storage_buffers_per_pipeline_layout: 0, max_sampled_textures_per_shader_stage: 16, max_samplers_per_shader_stage: 16, max_storage_buffers_per_shader_stage: 0, max_storage_textures_per_shader_stage: 0, max_uniform_buffers_per_shader_stage: 11, max_uniform_buffer_binding_size: 16384, max_storage_buffer_binding_size: 0, max_vertex_buffers: 8, max_buffer_size: 268435456, max_vertex_attributes: 16, max_vertex_buffer_array_stride: 255, min_uniform_buffer_offset_alignment: 256, min_storage_buffer_offset_alignment: 256, max_inter_stage_shader_components: 60, max_compute_workgroup_storage_size: 0, max_compute_invocations_per_workgroup: 0, max_compute_workgroup_size_x: 0, max_compute_workgroup_size_y: 0, max_compute_workgroup_size_z: 0, max_compute_workgroups_per_dimension: 0, max_push_constant_size: 96 }
Surface quality: high
Surface samples: 4
Surface size: Extent3d { width: 550, height: 400, depth_or_array_layers: 1 }
Player type: Object
SWF URL: ep.swf
Param menu: false
Param scale: noScale
Param allowScriptAccess: sameDomain
Param wmode: transparent
Param flashvars: sr=1
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined
Attribute 5: undefined
Attribute 6: undefined

# Page Info
Page URL: https://aidn.jp/ep/
SWF URL: https://aidn.jp/ep/ep.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.2088.76
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-11-03
Channel: nightly
Built: 2023-11-03T00:14:13.838Z
Commit: 8138b689195dd674f022efa7a8d83b62d34cb9ae
Is extension: true

# Metadata
width: 1000
height: 800
frameRate: 30
numFrames: 1
swfVersion: 10
backgroundColor: undefined
isActionScript3: true
uncompressedLength: 68925
