### ISSUE TITLE
Instances of a same sound should be limited in number

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1388]
[Steppenwolf 1-1](https://www.y8.com/games/steppenwolf_chapter_1_episode_1) has a bug in which a sound is played every frame if the spacebar is held down.

In Ruffle, there's no limit and the sound is played until the space bar is released.
Flash, however, seems to set a limit. The title of this bug report assumes this is a per-sound limit but this hasn't been confirmed (could this be a global or even a "per-script" limit?).

In both of the audio samples below, the spacebar is pressed and released only once:
[audio_diff.zip](https://github.com/ruffle-rs/ruffle/files/5435394/audio_diff.zip)

**Comment by Herschel** [comment]
It's probably a global sound channel limit; need to do some experimenting to determine what the limit actually is. Ruffle doesn't have a limit currently even though it should have at least some limit.

**Comment by Herschel** [comment]
Fixed by #2825. Sounds are limited to 32 instances.

**Comment by Toad06** [comment]
Hmm, for some reason I can still reproduce the issue. This happens on both desktop and web backends.
