### ISSUE TITLE
Nimball: Rewind - Game hangs after Beef Jack Studio logo

### ISSUE THREAD

**Issue by JimCarlTay** [ruffle-rs/ruffle#19068]
### Describe the bug

Related to issue #16635.

Pretty much self-explanatory.

Open the Kongregate or BubbleBox links to the game, then wait until after the Beef Jack Studio logo finishes. The game hangs afterward. In the case of the Flash Museum version, it hangs after "Play Game" is clicked.

### Expected behavior

The game should progress to the title screen and be able to go in-game, at least in a playable state.

### Content Location

https://www.kongregate.com/games/monkeynutz007/nimball-rewind (Link to game on Kongregate)
https://www.bubblebox.com/play/1985/nimball-rewind.htm (Link to game on BubbleBox)
https://flashmuseum.org/nimball-rewind/ (Link to game on Flash Museum)

### Affected platform

Browser's extension

### Operating system

Windows 10 (version 22H2)

### Browser

Brave 1.73.104

### Additional information

Ruffle browser extension build: December 25, 2024 nightly

**Comment by evilpie** [comment]
```
ERROR core/src/avm2/events.rs:429 Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x44c6d38 }) to handler FunctionObject(FunctionObject { ptr: 0x44c6048, name: Ok("Nimball/onSponsorComplete()") }) : ReferenceError: Error #1069: Property getFontMetrics not found on flash.text.engine.ElementFormat and there is no default value. core.ruffle.8341e5592963ba736f5f.js:1:52069
```

**Comment by Lord-McSweeney** [comment]
The current error is
```
Error dispatching event EventObject { type: "complete", class: flash.events::Event, ptr: 0x2ab4f00 } to handler FunctionObject(FunctionObject { ptr: 0x2af1040, name: "Nimball/onSponsorComplete()" }) : TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at flashx.textLayout.compose::TextFlowLine/makeBlock()
	at flashx.textLayout.compose::TextFlowLine/makeSelectionBlocks()
	at flashx.textLayout.compose::TextFlowLine/http://ns.adobe.com/textLayout/internal/2008::computePointSelectionRectangle()
	at flashx.textLayout.compose::TextFlowLine/http://ns.adobe.com/textLayout/internal/2008::selectionWillIntersectScrollRect()
	at flashx.textLayout.container::ContainerController/scrollToRange()
	at flashx.textLayout.edit::EditManager/finalizeDo()
	at flashx.textLayout.edit::EditManager/endCompositeOperation()
	at fl.text::TLFTextField/replaceText()
	at fl.text::TLFTextField/set text()
	at LevelBut/set level()
	at LevelSelectStep/initLevels()
	at LevelSelectStep()
	at com.l.game::MenuControl/init()
	at com.l.game::MenuControl()
	at com.l.game::MenuControl$/getInstance()
	at Nimball/initControl()
	at Nimball/onSponsorComplete()
	at flash.events::EventDispatcher/dispatchEventInternal()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.l.game::SponsorControl/onBeefFrame()
```

**Comment by thenickman100** [comment]
The game now works as of Ruffle 0.6.0 release!

**Comment by Lord-McSweeney** [comment]
This was probably fixed by some of the recent FTE/TLF work.

**Comment by JimCarlTay** [comment]
Only the Kongregate version is fixed. The other versions still aren't.

**Comment by Lord-McSweeney** [comment]
Flash Museum is using an outdated version of Ruffle, so the SWF is still not working there. I'm not sure what's going on with Bubblebox- seems like it fails to load Ruffle? On both sites, the SWFs work correctly when running them using the latest version of the desktop app.

**Comment by JimCarlTay** [comment]
Well, it appears that the extension on Firefox hasn't been updated yet on my end.
