### ISSUE TITLE
Weird behavior and hiding next steps (clickable texts)

### ISSUE THREAD

**Issue by hamzaelbarmaki1994** [ruffle-rs/ruffle#19137]
### Describe the bug

hi,
i was palying an exercice of math using ruffle as player but after question 1 the exercice behave weird  
doesn't shows next steps to respond the questions,
![Image](https://github.com/user-attachments/assets/8cea548a-7cf6-4ad4-b9dc-459818098f44)

note: it plays well on the old flashplayer32 locally (i want to use the online version to share it )

### Expected behavior

image speaks loud 
![Image](https://github.com/user-attachments/assets/cb97b846-8593-4a25-9092-6e6a76fc2eb2)

### Content Location

this is the link of swf https://bibliotheque.sesamath.net/public/voir/571

### Affected platform

Online demo

### Operating system

windows 10

### Browser

all browsers

### Additional information

even desktop  version has the same problem.

**Comment by Lord-McSweeney** [comment]
I can't reproduce this issue on the latest version of Ruffle, but I also can't reproduce it on the version that Ruffle was on when this report was filed. @hamzaelbarmaki1994 can you confirm that this issue is fixed?

**Comment by mathheb1-dotcom** [comment]
@Lord-McSweeney the issue remain it happens at question 2, 3 and so on 
the question 1 works as expected.

<img width="922" height="378" alt="Image" src="https://github.com/user-attachments/assets/f7f76cd8-dd96-447b-9fb9-a03eb12304ca" />
