### ISSUE TITLE
Reporting issues with a few swf files

### ISSUE THREAD

**Issue by WingFoxie** [ruffle-rs/ruffle#2088]
I tested all this in "https://ruffle.rs/demo/", with Firefox browser. Today.
For every side-by-side screenshot, The left is Ruffle, right is  Adobe Flash Player.
The link I provided is a page containing the swf file, not the direct link to the swf file, I don't really know how to get that link.

1. Coolio DJ
Link: https://www.newgrounds.com/portal/view/382393
Issue: Visual Difference (Only visual). As shown in the screenshot. 
![2020-12-25 08_44_53-2020-12-25 07_03_25-Greenshot png _ 1920•1080•24 _ Image Eye](https://user-images.githubusercontent.com/47227799/103112029-7e67d880-468d-11eb-9dec-98bf4878fcdc.png)

2. stream line
Link: https://www.newgrounds.com/portal/view/328399
Issue: Not Visual, Game gets out of sync of music with 1 beat, starting from this stage, shown in the screenshot. 
![2020-12-25 08_45_22-2020-12-25 06_57_08-Greenshot png _ 1920•1080•24 _ Image Eye](https://user-images.githubusercontent.com/47227799/103112053-b1aa6780-468d-11eb-840e-b61db07ad6fb.png)

(The game's a bit hard though, you have to survive to this stage to see the bug, so it might be a bit hard to test.)
(The Out-of-Sync is pretty obvious, you can even tell if it's your first try on ruffle)

3. Particles
Link: https://www.newgrounds.com/portal/view/357700
Issue: Not just "text missing shadows", But the "PLAY" button is harder to click on. The clickable area is supposed to be a rectangular surrounding the word "PLAY", but in ruffle, I have to click precisely on the black lines.
![2020-12-25 07_41_34-Adobe Flash Player 25](https://user-images.githubusercontent.com/47227799/103112068-c5ee6480-468d-11eb-8104-135d34611239.png)

Also the text got cut off a bit, like shown in the second screenshot.
![2020-12-25 07_44_38-Adobe Flash Player 25](https://user-images.githubusercontent.com/47227799/103112070-cedf3600-468d-11eb-8932-c4eb5460811a.png)

4. Four Second Fury
Link: https://www.newgrounds.com/portal/view/309403
Issue: Some text, like the title, are missing shadow. (Other than this the game works correctly.)
![2020-12-25 07_19_10-Adobe Flash Player 25](https://user-images.githubusercontent.com/47227799/103112074-d9013480-468d-11eb-8cd1-4ae822b96170.png)

5. Four Second Firestorm
Link: https://www.newgrounds.com/portal/view/345378
Issue: The issue is actually with the file, not with ruffle.
![2020-12-25 08_48_03-Adobe Flash Player 25](https://user-images.githubusercontent.com/47227799/103112087-f0d8b880-468d-11eb-8d3a-ad170a0ec571.png)

Some games detect if your are using Flash Player 9 or later, but their detection is flawed, and won't let you play with Flash Player 25 or something... says that "You are using flash player 8 or earlier"... How stupid!
Sometimes, with Adobe Flash Player, I can walk around this by pressing "Ctrl+Enter", skipping a few frames, skipping the check.
Maybe ruffle should be able to pretend to be a specific Flash Player version, and tell those files that you are running Adobe Flash Player 9?

6. 3D Missile (The Missile Game 3D HS)
Link: https://www.newgrounds.com/portal/view/363979
Issue: It looks like the game is rendered correctly. But the hit detection is completely wrong. I keep hitting the obstacle when I am clearly passing through the holes.
![2020-12-25 08_54_05-设置](https://user-images.githubusercontent.com/47227799/103112244-10241580-468f-11eb-8261-3d03aa695285.png)

7. Xevoz Showdown
Link: http://www.yy2k.com/game/Xevoz-Showdown/
Issue: When ruffle loads the game, first screen fades into black, that's it. So I can't play the game.
![2020-12-25 08_04_20-](https://user-images.githubusercontent.com/47227799/103112125-3301fa00-468e-11eb-90a6-db8ef00d807d.png)

8. Knife
Link: I couldn't find one, hmm...
Issue: It seems that the game is totally working. But noticed a "Volume" bar on the top right? It doesn't work!
And the music doesn't loop when it's supposed to.
![2020-12-25 08_07_35-Ruffle Web Demo — Mozilla Firefox](https://user-images.githubusercontent.com/47227799/103112175-896f3880-468e-11eb-82cd-b4eef42c2566.png)

9. Monster Frontier
Link: https://armorgames.com/play/17878/monster-frontier
Issue: First, If I use the offline version of Adobe Flash Player, error popped out (I see Error #2044 and #2048), but I can just ignore the error and play the game.
If I load the file in ruffle though, I can't get the game to load, it will just flash the first screen and never proceed.

10. Music in Motion
Link: https://www.newgrounds.com/portal/view/425852
Issue: It looks okay, until you actually start playing the game. The first stage the screen will roll, and you should keep going right. However, in ruffle, the "walkable area" doesn't scroll with the screen, therefore I can't proceed.

**Comment by n0samu** [comment]
I didn't have a chance to test all of these, but it looks like the issue with Music in Motion is fixed.

**Comment by ChrisCPI** [comment]
Here's what I found with all of these:
1. Looks better now, but the font for the score is still not correct (this likely only happens on the web).
2. Couldn’t test
3. Seems fixed now
4. Seems fixed now
5. I can’t seem to replicate this problem in Flash Player or Ruffle. Regardless, there is now an option to emulate player version as was described.
6. Still happening, as described in #8054.
7. Seems fixed now
8. No link provided, so I can't test
9. Seems fixed now
10. Seems fixed now

**Comment by ChrisCPI** [comment]
If the issues with the 2nd and 8th games still persist, please open new separate issues for those.
