### ISSUE TITLE
Texts missing and unexpected feature in 武斗纹章-时度

### ISSUE THREAD

**Issue by fsfsdfcsef** [ruffle-rs/ruffle#21893]
### Describe the bug

1.The texts of character selection and backpack are not displayed 

<img width="873" height="623" alt="Image" src="https://github.com/user-attachments/assets/8aae9cce-530d-4d9c-8300-5b3ebb7dc8b5" />

(Character selection)

2.Load save that save from a different scene will give you 2 useless lv.0 emblems with no image and can't be selected. These useless emblems shouldn't be appeared in the game.

<img width="786" height="627" alt="Image" src="https://github.com/user-attachments/assets/c57abeae-1650-4594-8d3e-fe83218c6518" />
(Backpack)

### Expected behavior

<img width="701" height="499" alt="Image" src="https://github.com/user-attachments/assets/3576e4cd-60a6-4b58-9ef3-49d4e806d5b5" />

(Character selection)

<img width="700" height="497" alt="Image" src="https://github.com/user-attachments/assets/13fd3040-f50d-46a9-b7ce-d301974ad60c" />

(Backpack)

### Content Location

https://www.mediafire.com/file/s11xco5hvmbebjo/武斗纹章-时度.zip/file

### Affected platform

Desktop app

### Operating system

Windows10 LTSC 2021

### Additional information

Console output on load save (texts in angle brackets is translation for Chinese)

```
2025-11-04T04:17:29.426583Z  INFO ruffle_core::focus_tracker: Focus is now on None
2025-11-04T04:17:29.492998Z  INFO avm_trace: 添加一个纹章数据    <<Add a emblem data>>
2025-11-04T04:17:29.493065Z  INFO avm_trace: 添加一个纹章数据    <<Add a emblem data>>
2025-11-04T04:17:29.493092Z  INFO avm_trace: 存在纹章数 2    <<Aquired emblem amount: 2>>
2025-11-04T04:17:29.493997Z  INFO avm_trace: 点击 [object SavePoint]    <<Click>>
2025-11-04T04:17:29.494351Z ERROR ruffle_core::loader: Error during URLLoader load of "file:///G:/flash%E6%B8%B8%E6%88%8F/%E4%B8%AD%E6%B5%81%E7%A8%8B%E6%B8%B8%E6%88%8F/%E6%AD%A6%E6%96%97%E7%BA%B9%E7%AB%A0/%E6%AD%A6%E6%96%97%E7%BA%B9%E7%AB%A0-%E6%97%B6%E5%BA%A6/File/event/daqi/1-1.xml": FetchError("系统找不到指定的文件。 (os error 2)")    <<Can't find specific file>>
2025-11-04T04:17:29.583656Z  WARN symphonia_bundle_mp3::demuxer: skipping junk at 17 bytes
2025-11-04T04:17:29.584016Z  WARN symphonia_bundle_mp3::demuxer: skipping junk at 17 bytes
2025-11-04T04:17:29.584260Z  WARN symphonia_bundle_mp3::demuxer: skipping junk at 17 bytes
2025-11-04T04:17:29.584484Z  WARN symphonia_bundle_mp3::demuxer: skipping junk at 17 bytes
2025-11-04T04:17:29.584625Z  WARN symphonia_bundle_mp3::demuxer: skipping junk at 17 bytes
2025-11-04T04:17:29.584734Z  WARN symphonia_bundle_mp3::demuxer: skipping junk at 17 bytes
2025-11-04T04:17:29.584843Z  WARN symphonia_bundle_mp3::demuxer: skipping junk at 17 bytes
2025-11-04T04:17:29.584989Z  WARN symphonia_bundle_mp3::demuxer: skipping junk at 17 bytes
2025-11-04T04:17:30.551728Z ERROR ruffle_core::loader: Error during URLLoader load of "file:///G:/flash%E6%B8%B8%E6%88%8F/%E4%B8%AD%E6%B5%81%E7%A8%8B%E6%B8%B8%E6%88%8F/%E6%AD%A6%E6%96%97%E7%BA%B9%E7%AB%A0/%E6%AD%A6%E6%96%97%E7%BA%B9%E7%AB%A0-%E6%97%B6%E5%BA%A6/File/event/daqi/2-1.xml": FetchError("系统找不到指定的文件。 (os error 2)")    <<Can't find specific file>>
2025-11-04T04:17:30.552109Z ERROR ruffle_core::loader: Error during URLLoader load of "file:///G:/flash%E6%B8%B8%E6%88%8F/%E4%B8%AD%E6%B5%81%E7%A8%8B%E6%B8%B8%E6%88%8F/%E6%AD%A6%E6%96%97%E7%BA%B9%E7%AB%A0/%E6%AD%A6%E6%96%97%E7%BA%B9%E7%AB%A0-%E6%97%B6%E5%BA%A6/File/event/daqi/lamp.xml": FetchError("系统找不到指定的文件。 (os error 2)")    <<Can't find specific file>>
2025-11-04T04:17:30.754041Z  INFO avm_trace: 创建地图数据    <<Create map data>>
2025-11-04T04:17:30.758658Z  INFO avm_trace: 解析 tiled    <<Parse tiled>>
2025-11-04T04:17:30.759144Z  INFO avm_trace: 解析 zs    <<Parse zs>>
2025-11-04T04:17:30.793758Z  WARN symphonia_bundle_mp3::demuxer: skipping junk at 17 bytes
2025-11-04T04:17:30.843674Z  INFO avm_trace: 执行事件： initLeft    <<Start event>>
2025-11-04T04:17:30.843693Z  INFO avm_trace: 初始化左边人设情况    <<Initialize character status on the left>>
2025-11-04T04:17:30.843696Z  INFO avm_trace: 0
2025-11-04T04:17:30.843743Z  INFO avm_trace: 1
```

“Can't find specific file” error is normal, source website doesn't have this resource either

**Comment by kjarosh** [comment]
This has been fixed already on Linux desktop with glyph fallback & font sorting:

<img height="300" alt="Image" src="https://github.com/user-attachments/assets/1b2bb9a9-9dde-480a-a077-e9e5f3cf9fd3" />

Windows client doesn't have font sorting implemented yet, similarly web.

**Comment by fsfsdfcsef** [comment]
The useless emblem issue have fixed on 2025-12-26 version, but it seems still can't display the glyphs
![捕获.PNG](https://github.com/user-attachments/assets/0017907e-683f-4563-97b1-caff00d00283)
web server: iis
browser: edge

**Comment by ukuq** [comment]
[FallbackFont.zip](https://github.com/user-attachments/files/24916066/FallbackFont.zip)

```js
window.RufflePlayer.config = {
        fontSources: [
            "../out/FallbackFont.swf",
            // "../out/EmojiFont.swf",
        ],
        defaultFonts: {
            sans: [
                "fallback",
                // "emoji",
            ]
        }
    }
```

Maybe this can help u
