### ISSUE TITLE
Error on http://www.brettmarvin.co.uk/

### ISSUE THREAD

**Issue by jkbbwr** [ruffle-rs/ruffle#2866]
# Error Info
Error name: Error
Error message: panicked at 'called `Option::unwrap()` on a `None` value', core/src/loader.rs:457:42
Error stack:
```
Error: panicked at 'called `Option::unwrap()` on a `None` value', core/src/loader.rs:457:42
    at s.wbg.__wbg_new_df6e6ab7a65c4c4d (<anonymous>:3:6318)
    at std::sync::once::Once::call_once::{{closure}}::h7141d078b1ea013f (chrome-extension://fnhgbhiojongfdnnhboocbiaicomjpmc/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1265]:0x24e3c9)
    at std::sync::once::Once::call_inner::h02eac160d339afc2 (chrome-extension://fnhgbhiojongfdnnhboocbiaicomjpmc/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[1528]:0x27e7a0)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::hf48d3d3ee3d10801 (chrome-extension://fnhgbhiojongfdnnhboocbiaicomjpmc/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4309]:0x3537a0)
    at std::panicking::rust_panic_with_hook::h123718ba3bf480af (chrome-extension://fnhgbhiojongfdnnhboocbiaicomjpmc/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3299]:0x32c417)
    at std::panicking::begin_panic_handler::{{closure}}::hf393a82e58397bd2 (chrome-extension://fnhgbhiojongfdnnhboocbiaicomjpmc/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[3916]:0x3495ce)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h2ff2cfc953878925 (chrome-extension://fnhgbhiojongfdnnhboocbiaicomjpmc/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4655]:0x358eda)
    at rust_begin_unwind (chrome-extension://fnhgbhiojongfdnnhboocbiaicomjpmc/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4526]:0x3574b8)
    at core::panicking::panic_fmt::h285dc015a87be5a4 (chrome-extension://fnhgbhiojongfdnnhboocbiaicomjpmc/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4657]:0x358f3e)
    at core::panicking::panic::h0abe4e7a620ae568 (chrome-extension://fnhgbhiojongfdnnhboocbiaicomjpmc/dist/40caf2b45c20a1522895df5ec7f369c3.wasm:wasm-function[4460]:0x35637d)
```

# Player Info
Allows script access: true

# Page Info
Page URL: http://www.brettmarvin.co.uk/
SWF URL: http://www.brettmarvin.co.uk/imagechanger_home.swf

# Browser Info
Useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4143.2 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-25
Channel: nightly
Built: 2021-01-25T01:05:41.178Z
Commit: 32fd3fb71befbceecbba7c73d08af5ddd0f5a3d0

**Comment by relrelb** [comment]
Panic was fixed by #6004. However, loading external images is currently not implemented yet. #2056 is related.

**Comment by Toad06** [comment]
Implemented by #6547 but the issue persists for some reason.

**Comment by n0samu** [comment]
This SWF uses PlaceObject2 tags with `colorTransform: CXFORMWITHALPHA`, varying the `alphaMultTerm` to fade the image in and out. `colorTransform` is supposedly fully implemented in Ruffle, but I have a feeling something about this was missed.

**Comment by n0samu** [comment]
I was wrong in diagnosing this issue. The movie uses code like this:
`loadMovie("flash/home-image1.jpg","_root.pic1");`
`pic1` is an empty button placed on the timeline. The code does not work because of the problem I explained in #9704.

**Comment by n0samu** [comment]
This was regressed by #11045 and is now panicking again:

Error message: panicked at core/src/loader.rs:2027:54:
called `Option::unwrap()` on a `None` value
Error stack:
```
339/__wbg_get_imports/imports.wbg.__wbg_new_a64e3f2afc2cf2f8@moz-extension://056d6ecb-8d62-4b0d-8a0c-9b82c8483fc5/dist/339.js:2624:21
core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a435d7beef43b50@:wasm-function[10793]:0xa1f551
std::panicking::rust_panic_with_hook::h62090d3fc0630473@:wasm-function[6608]:0x906d55
core::panicking::panic_fmt::hd79411a297d06dc8@:wasm-function[10505]:0xa19083
core::panicking::panic::hd37d8d0a98259c88@:wasm-function[10076]:0x9ff18b
ruffle_core::loader::Loader::movie_loader_complete::h78d687f5d1063f8d@:wasm-function[730]:0x22fd7a
ruffle_core::loader::Loader::movie_loader_data::h423825ef2c8d3199@:wasm-function[3635]:0x7719b2
ruffle_core::loader::Loader::movie_loader::{{closure}}::hc4b884964fb49e31@:wasm-function[793]:0x2a3cb9
<ruffle_web::navigator::WebNavigatorBackend as ruffle_core::backend::navigator::NavigatorBackend>::spawn_future::{{closure}}::heb2d58e3ea262753@:wasm-function[1283]:0x443fa6
wasm_bindgen_futures::queue::Queue::new::{{closure}}::h007033b9284c7696@:wasm-function[3736]:0x787b25
<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::he60536ce30c58d9e@:wasm-function[11740]:0xa3a8aa
closure5627 externref shim@:wasm-function[12057]:0xa46071
__wbg_adapter_84@moz-extension://056d6ecb-8d62-4b0d-8a0c-9b82c8483fc5/dist/339.js:310:10
real@moz-extension://056d6ecb-8d62-4b0d-8a0c-9b82c8483fc5/dist/339.js:271:20
```

**Comment by Lord-McSweeney** [comment]
This unwrap in `Loader::movie_loader_complete` is being triggered: 
```
        } else if let Some(dobj) = dobj {
            // This is a load of an image into AVM1 - add it as a child of the target clip.
            if dobj.as_movie_clip().is_none() {
                let mc = target_clip.as_movie_clip().unwrap();
```
