### ISSUE TITLE
Dynamic text variable location path

### ISSUE THREAD

**Issue by Tempy111** [ruffle-rs/ruffle#4088]
I'm trying to fix this myself but it's... slghtly above my very basic RUST skills..

when you create a button, which has the text being dynamic via a variable which is NOT referenced to Root, it uncorrectly sets a path for the variable, and thus can't find it.

In flash, create a  button or maybe even just a normal clip called 'TextBoxClip'. Inside create a button with no instance name, inside that put a textbox called 'TextBox1', you could do:
`tellTarget (_root.TextBoxClip){
TextBoxText1 = "This is text";`

and it would display that text in the text field..

However, with Ruffle, it wants to use the uninstanced clip as part of the path. Flash has a weird quirk in AS1 and i think AS2 (i'm not sure about AS3) where it didn't even include the button name if it had an instance name.. I'm not quite sure what Ruffle is adding in it's place, probably a null value if the button is name instanced.

if the button is given an instance name, it works fine in ruffle, but since it should work without a name, (in flash didn't check the name anyway) it's a bit of a bug.

I was trying to find where in the ruffle code it works out and checks the path but the best I could find is from line 632 to 648 in the  'ruffle/core/src/display_object/edit_text.rs' file

**Comment by Herschel** [comment]
Related to https://github.com/ruffle-rs/ruffle/issues/1029, button and text fields can't have instance names in SWFv4/5.
Also some what related to https://github.com/ruffle-rs/ruffle/issues/1513 as I think "fake" instance paths are returned if you try to be clever and actually grab the button, for example by doing `_level0.instance1` or `_parent` from a clip inside the button.

**Comment by Herschel** [comment]
Looking at it a bit more, and the behavior is a little strange:

 * Even in SWFv6+, the behavior still occurs; if the text field is the child of a button, the binding will be registered on the parent instead. 
 * This also happens for a variable like `_root.button.foo`, because `foo` is a property of `button`. This actually binds to `_root.foo`.
 * It also includes `_root.button.button.button....button.foo`. This only binds to `_root.foo`, even if there is only one `button` clip...! I think the text field bindings must revert to an "SWF5" mode, and this is behavior is caused by the SWF5 buttons returning their parent, i.e. `_level0` instead of `_level0.button`, so repeated accesses of `_root.button` circle back to `_root`.
 * However, setting `textField.variable = "_root.button.foo"` does not exhibit SWF5 behavior. This binds to "foo" from the button object.

**Comment by Herschel** [comment]
I also think this is causing #2181.

**Comment by Tempy111** [comment]
mm.. so this is a interesting one to fix if it seams to be the root for a few noted issues..

really.. I think a bit of code needs to somehow check if the textfield is in a button, and if so, not to include it in the path.. this is a bit annoying... and far beyond me I think... the 
'ruffle/core/src/display_object/edit_text.rs' file does seam to have stuff for variable binding in the set_variable function (ln 642) so.. maybe there..

**Comment by Lord-McSweeney** [comment]
Fixed by #12541.

**Comment by n0samu** [comment]
The more complicated cases described in Mike's comment probably are not fixed, so until someone makes samples and a new issue for those, I think we should keep this issue open.

**Comment by n0samu** [comment]
Most of this was indeed fixed by #12541, but the second and third points Mike raised still aren't fully addressed. I opened #12589 to track that.
