### ISSUE TITLE
[regression?] slower starting times

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#548]
@Herschel,

after c586991, starting the Linux binary on my laptop takes over four times longer.

Before c586991: 

```
$ time ruffle ./free_culture.swf 

real	0m0.811s
user	0m0.373s
sys	0m0.149s
```

After c586991:

```
$ time ./ruffle free_culture.swf 
WARNING: radv is not a conformant vulkan implementation, testing use only.

real	0m4.998s
user	0m3.930s
sys	0m0.252s
```

BTW, I simply close the application once the window displays the first frame.

The testing file can be found at https://randomfoo.net/oscon/2002/lessig/free_culture.swf.

I can reproduce the issue with all SWF files I have.

**Comment by Herschel** [comment]
I noticed this too. I think `wgpu`/`gfx-rs` is doing a lot of `log` debug spew, even in release builds. Have to see whether it's possible to disable `log` for `gfx` (or maybe disable it for ourslevesin release builds, too, at least up to to warn or error level)

**Comment by Dinnerbone** [comment]
You're 100% sure it's that commit (bisected, I guess?), and this is the desktop application correct? That commit should have only affected web.

I can imagine that the wgpu backend could have slowed things down, as it's not as optimized as it should be. We took liberties with the GL backend that aren't strictly allowed or proper, and working around this added a bit of cost.

**Comment by ousia** [comment]
@Dinnerbone, I didn’t bisect. The difference is between this two binaries from:

```
2020-05-03T00:23:17.000Z        3.3 MB         ruffle_linux_2020-05-03_c586991.tar.gz
2020-05-01T00:25:53.000Z        3.2 MB         ruffle_linux_2020-05-01_8384847.tar.gz
```

I mentioned commit c586991 because I think it was also the main commit for that pull request-

**Comment by Dinnerbone** [comment]
Turns out you need a better graphics card than I have to do actual profiling of vulkan, but I have a fair good idea of what's slowing us down. I want to land some basic rendering tests before attempting to blindly optimise though.

**Comment by Dinnerbone** [comment]
@ousia could you please try after tonights build is made?

**Comment by ousia** [comment]
@Dinnerbone, many thanks for build fe4676a.

Times are great again (see below), but latest build only displays a blank screen with https://randomfoo.net/oscon/2002/lessig/free_culture.swf.

```
$ time ./ruffle free_culture.swf 
WARNING: radv is not a conformant vulkan implementation, testing use only.

real	0m0.783s
user	0m0.388s
sys	0m0.142s
```

**Comment by Dinnerbone** [comment]
@ousia oh no! Fast isn't good if it doesn't work 😅 

Do other swfs play? What colour is the blank screen? Do you hear audio (maybe try some other swfs to test that)?

**Comment by Herschel** [comment]
I was getting this too; it would fix itself by resizing the window. I think it's fixed in #573 by creating the window with the proper dimensions to account for hidpi displays.

**Comment by ousia** [comment]
@Herschel, many thanks for your commit. I hope it fixes the issue. I’ll check this tomorrow.

I’m afraid to report that maximizing (or otherwise resizing) the window doesn’t fix the issue for me.

**Comment by ousia** [comment]
@Herschel, I’m afraid that build from commit f034471 doesn’t fix the blank screen for me.

**Comment by ousia** [comment]
@Herschel and @Dinnerbone,

I have just checked latest build against latest Fedora and it works perfectly fine.

Many thanks for your work. I’m closing the issue myself.

**Comment by Herschel** [comment]
Thank you for testing!
