### ISSUE TITLE
annoying sound issues BEE BOXING

### ISSUE THREAD

**Issue by flashliberty5467** [ruffle-rs/ruffle#5923]
### Describe the bug

just play the game and we have the issues with sound

but otherwise the game works just fine

https://user-images.githubusercontent.com/64484245/147374942-7ee7a2f0-9ee0-4438-8aac-25b1c236b755.mp4

https://www.bubblebox.com/play/95/bee-boxing.htm

### Expected behavior

for the game to play without annoying sounds  as it is in order to enjoy the game i have to mute my chromebook

### Affected platform

Browser's extension

### Operating system

ChromeOS

### Browser

Version 96.0.4664.111 (Official Build) (64-bit)

**Comment by relrelb** [comment]
Thanks for the report! Unfortunately, this doesn't reproduce for me in the latest nightly (2021-12-22). Could it be that you just use an older release? (I suspect this has been fixed by #5657, which was landed in nightly 2021-11-28)

**Comment by flashliberty5467** [comment]
@relrelb i just updated the extension to the latest vershion today and i still have the same issues mine now is  (2022-01-15)



https://user-images.githubusercontent.com/64484245/149639944-f2459989-4b19-4123-a061-df887501e433.mp4

**Comment by relrelb** [comment]
After a short investigation, this looks like another case of https://github.com/ruffle-rs/ruffle/issues/993#issuecomment-675182938.
In `frame 5\DoAction`:
```as
if (this.kia == true) {
    this.lieDown = this.lieDown + 1;
    if (this.lieDown >= 10) {
        var _loc4_ = aktie.getNextHighestDepth();
        var _loc3_ = aktie.attachMovie("mcKruis","kruis" + _loc4_,_loc4_);
        _loc3_._x = this._x;
        _loc3_._y = this._y;
        _loc3_.kruisnr = this.commander.commanderNr;
        if (this.commander.control == true) {
            if (winnaar == null) {
                speelSimpelSFX("man_lost");
            }
        }
        this.kia = false; // <-- Added manually!!!
        this.removeMovieClip();
    }
}
```
In Flash, `this.removeMovieClip()` causes `this.kia` to be `undefined` in the next frames, preventing more instances of `mcKruis` (the cross) from being created.
In Ruffle, however, `this.kia` remains `true`, so new `mcKruis` instances keep getting created on each frame. Manually adding `this.kia = false` seems to solve the problem.
Will be fixed by #5492.
