### ISSUE TITLE
Error on https://www.newgrounds.com/portal/view/556643. Console is screaming.

### ISSUE THREAD

**Issue by lempamo** [ruffle-rs/ruffle#8133]
### Describe the bug

I'm using the latest nightly build of Ruffle for Firefox. This happened during an attempt to play the seminal flash game [K.O.L.M. ](https://www.newgrounds.com/portal/view/556643)Upon reaching the main menu scene I get this in the console:
```
20:54:52.023 AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x537a46d4 }))))
20:54:52.024 ReferenceError: Error #1069: Property setPixels not found on flash.display.BitmapData and there is no default value.
20:54:52.025 AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x537a46d4 }))))
20:54:52.026 ReferenceError: Error #1069: Property setPixels not found on flash.display.BitmapData and there is no default value.
20:54:52.027 AVM2 error: Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x537a46d4 }))))
20:54:52.027 ReferenceError: Error #1069: Property setPixels not found on flash.display.BitmapData and there is no default value.
20:54:52.028 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x12c0478 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x1d6436c }))) : AvmError(Object(ErrorObject(ErrorObject(GcCell(Gc { ptr: 0x537a46d4 }))))) 
```

Thereafter, the console is reduced to outputting a series of A's and unknown characters. On top of that, the game runs so slow it is unplayable.

### Expected behavior

I would expect the main menu to reveal itself in a decent amount of time, and not at an absurdly low framerate. That, and for the console to not scream at me.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Mozilla Firefox 104

**Comment by n0samu** [comment]
I'm also getting this error that I think is related:
```
Uncaught TypeError: TextDecoder.decode: Decoding failed.
    i ruffle_web-wasm_extensions.js:20
    __wbindgen_string_new ruffle_web-wasm_extensions.js:517
    A ruffle_web-wasm_extensions.js:198
    c ruffle_web-wasm_extensions.js:175
    __wbg_requestAnimationFrame_61bcf77211b282b7 ruffle_web-wasm_extensions.js:792
    R ruffle_web-wasm_extensions.js:213
    __wbg_requestAnimationFrame_61bcf77211b282b7 ruffle_web-wasm_extensions.js:791
    A ruffle_web-wasm_extensions.js:198
    c ruffle_web-wasm_extensions.js:175
    __wbg_requestAnimationFrame_61bcf77211b282b7 ruffle_web-wasm_extensions.js:792
    R ruffle_web-wasm_extensions.js:213
    __wbg_requestAnimationFrame_61bcf77211b282b7 ruffle_web-wasm_extensions.js:791
    A ruffle_web-wasm_extensions.js:198
    c ruffle_web-wasm_extensions.js:175
```
repeated 2 times from ruffle_web-wasm_extensions.js:20:29

**Comment by hatal175** [comment]
The slowness was solved when implementing setPixels. Working on pull request.

**Comment by n0samu** [comment]
For the record, the "screaming console" error still doesn't seem to be fixed.

**Comment by hatal175** [comment]
Reopen then?

**Comment by Lord-McSweeney** [comment]
This works better now. There is extreme lag (around 15 seconds per frame), as well as "A script in this movie has taken too long to execute and has been terminated". There are the following errors:
<code>

ERROR core/src/avm2/activation.rs:936 ReferenceError: Error #1069: Property invalidate not found on flash.display.Stage and there is no default value.

ERROR core/src/display_object/movie_clip.rs:2039 Got AvmError(Object(ErrorObject(ErrorObject { ptr: 0x1f486d0 }))) when constructing AVM2 side of movie clip of type com.newgrounds.components::APIConnector

ERROR core/src/display_object/movie_clip.rs:2363 Error occured when running AVM2 frame script: RustError("Cannot set undefined property ::componentInspectorSetting on Some(com.newgrounds.components::APIConnector)")

</code>
