### ISSUE TITLE
Canabalt: Cannot start game

### ISSUE THREAD

**Issue by xerz-one** [ruffle-rs/ruffle#8801]
### Describe the bug

When pressing X or C to start a new game, nothing happens. This was tested in both the desktop client and the Firefox extension.

### Expected behavior

A new game starts, loading the corresponding world

### Affected platform

Found on desktop app and web extension

### Operating system

Arch Linux

### Browser

Firefox 108.0

### Additional information

Log example for the latest Linux desktop nightly:

```
[2022-12-15T22:10:46Z ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x55f2329bae00 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x55f22ffc1a58 }))) : RustError("VerifyError: Trait _p in class BG has same name as trait _p in class FlxSprite, but does not override it")
[2022-12-15T22:10:48Z ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x55f232444bc0 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x55f22ffc1a58 }))) : RustError("Resolved parameter type com.adamatomic.Canabalt::BG is unresolvable, not a class, null, or undefined")
```

**Comment by Lord-McSweeney** [comment]
Fixed by #9506.

**Comment by xerz-one** [comment]
Game still doesn't work with error `panicked at 'called `Option::unwrap()` on a `None` value', core/src/bitmap/bitmap_data.rs:1231:22`, should I open a new ticket?

**Comment by waspennator** [comment]
Can confirm, this pops up in the error logs now, have a feeling one of the array.removeat PR's regressed it.

Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1333c10 }) to handler FunctionObject(FunctionObject { ptr: 0x125df90 }) : RustError("VerifyError: Trait removeAt in class FlxArray has same name as trait removeAt in class Array, but does not override it")

**Comment by waspennator** [comment]
Update, should be fixed by #10168
