### ISSUE TITLE
Adventure Ponies: Stuck loading

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#8903]
### Describe the bug

I think the first time I remembered testing this, it kept cycling across a bunch of random screens in a non stop loop, now it just gets stuck on the loading screen on the latest ruffle.

https://www.numuki.com/game/mlp-adventure-ponies/

Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x277bca8 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x2809a64 }))) : RustError("Property does not exist: Multiname { ns: Multiple(Gc { ptr: 0x1cdc8d4 }), name: Some(\"unescape\"), params: [], flags: (empty) }")
$web_sys::features::gen_console::console::error_1::hd0bae7ea2787150d	@	018f336e:0x4d3ca9 ﻿

### Expected behavior

It should actually load up to the title screen.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by n0samu** [comment]
Can you copy the error as text instead of an image and edit your issue? Thanks

**Comment by waspennator** [comment]
Is that better now?

**Comment by Lord-McSweeney** [comment]
Does this have something to do with the global `escape()` and `unescape()` functions in ActionScript?

**Comment by n0samu** [comment]
Good catch, adding the `unimplemented` label to this issue.

**Comment by waspennator** [comment]
> Good catch, adding the `unimplemented` label to this issue.
> 
> And yes waspennator, that's better.

Gotcha, I think #8543 might need the unimplemented tag since I believe that requires "netconnection"

**Comment by n0samu** [comment]
Done, thanks

**Comment by waspennator** [comment]
Game is still broken as of the latest nightly spewing this out in the logs.

Error dispatching event EventObject(EventObject { type: "complete", class: flash.events::Event, ptr: 0x1779fa8 }) to handler FunctionObject(FunctionObject { ptr: 0x2f8df98 }) : RustError("Property does not exist: Multiname { ns: Multiple([Namespace(Private(\"\")), Namespace(Private(\"\")), Namespace(Namespace(\"\")), Namespace(Namespace(\"com.splashworks\")), Namespace(PackageInternal(\"com.splashworks\")), Namespace(Namespace(\"http://adobe.com/AS3/2006/builtin\")), Namespace(Protected(\"com.splashworks:Doc\")), Namespace(StaticProtected(\"com.splashworks:Doc\")), Namespace(StaticProtected(\"flash.display:MovieClip\")), Namespace(StaticProtected(\"flash.display:Sprite\")), Namespace(StaticProtected(\"flash.display:DisplayObjectContainer\")), Namespace(StaticProtected(\"flash.display:InteractiveObject\")), Namespace(StaticProtected(\"flash.display:DisplayObject\")), Namespace(StaticProtected(\"flash.events:EventDispatcher\")), Namespace(StaticProtected(\"Object\"))]), name: Some(\"unescape\"), params: [], flags: (empty) }")

**Comment by waspennator** [comment]
[adventure-ponies.zip](https://github.com/ruffle-rs/ruffle/files/10926833/adventure-ponies.zip)

Downloaded it from Flashpoint to check and see and it seems to work alright from the downloaded copy I tried (Game seems to use XML and also have another SWF for the audio)

However, there seems to be a new problem when running it that way. No matter how many times you try and select a pony to start, the game will never start and toss this up in the command prompt.

[Adventure Ponies bug.log](https://github.com/ruffle-rs/ruffle/files/10926884/Adventure.Ponies.bug.log)

**Comment by waspennator** [comment]
Testing it out and looking into it, I think this swf is currently broken on

"Modifying an XML object is not yet implemented"

**Comment by waspennator** [comment]
Tested on latest nightly on desktop, game is now capable of starting up.
