### ISSUE TITLE
Error on http://new.weedtowonder.org/

### ISSUE THREAD

**Issue by danielhjacobs** [ruffle-rs/ruffle#8958]
Caused by right-click -> play (SWF doesn't get past loading without that workaround currently). Other error messages in console include:
```
Got RustError("Property does not exist: Multiname { ns: Single(Namespace(\"flash.text.engine\")), name: Some(\"BreakOpportunity\"), params: [], flags: (empty) }") when constructing AVM2 side of movie clip of type fl.text::TCMText

Got RustError("VerifyError: Trait videoWidth in class VideoPlayer marked as override, does not override any other trait") when constructing AVM2 side of movie clip of type fl.video::FLVPlayback

Got RustError("Non-public property http://adobe.com/AS3/2006/builtin::settings not found on Object") when constructing AVM2 side of movie clip of type w2w_fla::MainTimeline
```

I know the SWF may be too complex for now, but the crash seems similar to https://github.com/ruffle-rs/ruffle/issues/5330, which is why I'm reporting it.

# Error Info
Error name: Error
Error message: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
Error stack:
```
Error: panicked at 'Stage must always have a root movie', core/src/display_object/stage.rs:580:9
    at imports.wbg.__wbg_new_f9bb493369a83c12 (chrome-extension://donbcfbmhbcapadipfkeojnmajbakjdc/dist/966.js:640:21)
    at std::sync::once::Once::call_once::{{closure}}::h07c839951d6d0b0f (wasm://wasm/018ff4e6:wasm-function[1095]:0x2bb1e7)
    at std::sys_common::once::generic::Once::call::h62f79875d8dd2a00 (wasm://wasm/018ff4e6:wasm-function[1400]:0x3215a4)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h5a01fde47a9be61a (wasm://wasm/018ff4e6:wasm-function[5064]:0x4b50de)
    at std::panicking::rust_panic_with_hook::he04cb00575f2a1e3 (wasm://wasm/018ff4e6:wasm-function[3744]:0x476567)
    at core::panicking::panic_fmt::h586d720a90aa8503 (wasm://wasm/018ff4e6:wasm-function[5305]:0x4b9f15)
    at core::option::expect_failed::h1e9a9cbb22bbd6ac (wasm://wasm/018ff4e6:wasm-function[5981]:0x4cd306)
    at ruffle_core::display_object::stage::Stage::root_clip::h08fdee4bec874afd (wasm://wasm/018ff4e6:wasm-function[3749]:0x47697d)
    at ruffle_web::Ruffle::tick::h5ebf2eb5e40a6af5 (wasm://wasm/018ff4e6:wasm-function[646]:0x1f9aa3)
    at ruffle_web::Ruffle::new_internal::{{closure}}::{{closure}}::{{closure}}::h827cf3c1225c1c3e (wasm://wasm/018ff4e6:wasm-function[6225]:0x4d5668)
```

# Player Info
Allows script access: true
Renderer: WebGL

# Page Info
Page URL: http://new.weedtowonder.org/
SWF URL: http://new.weedtowonder.org/w2w-home.swf

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2022-12-29
Channel: nightly
Built: 2022-12-29T00:16:34.344Z
Commit: 8b9bae8ca610fa6081ef84a267453936784c2ac5
Is extension: true

# Metadata
width: 1024
height: 768
frameRate: 24
numFrames: 2
swfVersion: 10
backgroundColor: #FFFFFF
isActionScript3: true
uncompressedLength: 882912

**Comment by n0samu** [comment]
This is fixed by #8909

**Comment by Lord-McSweeney** [comment]
The SWF still hangs on the loading screen, even if it's opened in a new tab on the web or on the desktop version. There isn't anything reported in the console, though.

**Comment by danielhjacobs** [comment]
It progresses when you right click it and click play (however with several error messages in the console and issues). I think Loader.unload would need to be functional before it would work without that workaround.
