### ISSUE TITLE
the Kill Kar II: Revenge: Loud audio when turning and performance dips

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#9086]
### Describe the bug

https://www.newgrounds.com/portal/view/519830?emulate=flash
From my testing i've noticed 2 specific issues with this game, the first seems to be consistent across all versions of Ruffle and the second seems to be only on NG's build and on desktop.

1: When turning your car in the arena, the audio that plays when you turn will get real damn loud as soon as you stop. I've compared it between flash and ruffle and Flash doesn't blow out my ear drums every time I turn for a second or so. Easiest way to trigger it is to turn left or right for a second or so then let go. (Highly suggest lowering the volume when trying this)

2: When running the web version of ruffle with the canvas renderer, the performance is rock solid albeit with missing blood effects and the arena floor being black (I'm presuming because of bitmap.draw being needed), but when I try it on NG or desktop, the arena floor and the blood effects seem to show up fine, but performance takes a hit as soon as I ram full speed into a ped.

### Expected behavior

For my eardrums not to get blown out every time I turn and for ruffle to not freeze up on desktop or NG when I run full speed into a ped.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 108

**Comment by Lord-McSweeney** [comment]
The second point should have been fixed by #9077.

**Comment by waspennator** [comment]
Trying it out again, I don't believe that actually changed anything about the second point. The game still noticably freezes up for a bit when ramming full speed into an enemy, on NG with the webgl-wgpu build or on Desktop.

**Comment by waspennator** [comment]
Testing again as of the latest nightly, the game still freezes for a small bit once you drive into a ped at the start of a level, but the game doesn't seem to stutter and lag like hell like it did before now after that.

**Comment by waspennator** [comment]
Still a problem as of latest nightly.

**Comment by TomFulp** [comment]
The braking sound issue was fixed in the NG version of Kill Kar 2 with an SWF update. Here is a link to the original SWF, for anyone who wants to solve the original bug:

https://www.newgrounds.com/dump/item/49a37e2af6ce05c539f9683e627aab4e

**Comment by waspennator** [comment]
Still occuring with the og unfixed version on latest nightly even with #22154

**Comment by waspennator** [comment]
Game doesnt blow out my eardrums anymore turning and dont notice lag when ramming so i guess its fixed now.
